USE employees;
SHOW TABLES;
DESCRIBE employees;
DESCRIBE current_dept_emp;
DESCRIBE departments;
DESCRIBE dept_emp;
DESCRIBE dept_emp_latest_date;
DESCRIBE dept_manager;
DESCRIBE salaries;
DESCRIBE titles;
SHOW CREATE TABLE dept_manager;